theme: jekyll-theme-slate
title: Josh's Data Science Blog and Portfolio.
description: My data science grad school journey. Click the button to follow.
    
authors: 
    Josh:
        name: Josh Butch
        intro: Data Science/Engineering Grad Student
        avatar: https://i.imgur.com/vFHCxld.jpg    

header-links:
    email: jbutch@regis.edu
    linkedin: https://www.linkedin.com/in/joshbutch/
  
google-analytics: UA-116290644-1 
