theme: jekyll-theme-architect

title: Josh's Data Science Blog and Portfolio.

description: My data science grad school journey. Please Stay Tuned!

avatar: https://github.com/joshbutch/Josh-Key-Info/blob/master/Josh%20professional%20photo.jpg

plugins:
  - jekyll-seo-tag

footer-links:
  email: jbutch@regis.edu
  linkedin: https://www.linkedin.com/in/joshbutch/
  
google-analytics: UA-116290644-1 
