theme: jekyll-theme-tactile

title: Josh's Data Science Blog and Portfolio.

description: My data science grad school journey. Please Stay Tuned!

footer-links:
  email: jbutch@regis.edu
  linkedin: https://www.linkedin.com/in/joshbutch/
  
google-analytics: UA-116290644-1 

