theme: jekyll-theme-tactile

title: Josh's Data Science Blog and Portfolio.

description: My data science grad school journey. Please Stay Tuned!

avatar: https://github.com/joshbutch/Josh-Key-Info/blob/master/Josh%20professional%20photo.jpg

footer-links:
  email: jbutch@regis.edu
  linkedin: https://www.linkedin.com/in/joshbutch/
  
google-analytics: UA-116290644-1 

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-116290644-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-116290644-1');
</script>

