theme: jekyll-theme-slate
title: Josh's Data Science Blog and Portfolio.
description: Final Graduate Practicum Project - Regis University - College of Computer & Information Science - Data Science Program
    
authors: 
    Josh:
        name: Josh Butch
        intro: Data Science Grad Student
        avatar: https://i.imgur.com/vFHCxld.jpg    

header-links:
    email: jbutch@regis.edu
    linkedin: https://www.linkedin.com/in/joshbutch/
  
google-analytics: UA-116290644-1 
