theme: jekyll-theme-tactile
title: Josh's Data Science Blog and Portfolio.
description: I am currently a data science grad student at Regis University in Denver, CO. I plan on using GitHub Pages to document my grad school journey and publish my projects. Please bookmark and check back regularly!
